options.general.attribute.descriptor.live.template:
    text: 템플리트//Live Template
options.general.color.descriptor.vcs.diff.separator.background:
    text: Folded unchanged fragments//배경
options.html.attribute.descriptor.comment:
    text: 주석
options.html.attribute.descriptor.tag:
    text: 꼬리표
options.java.attribute.descriptor.abstract.method:
    text: 메소드//Abstract method
options.java.attribute.descriptor.implicit.anonymous.parameter:
    text: 매개 변수//Implicit anonymous class parameter
options.java.attribute.descriptor.inherited.method:
    text: 메소드//Inherited method
options.java.attribute.descriptor.javadoc.markup:
    text: 주석//JavaDoc//Markup
options.java.attribute.descriptor.javadoc.tag:
    text: 주석//JavaDoc//꼬리표
options.java.attribute.descriptor.javadoc.tag.value:
    text: 주석//JavaDoc//Tag value
options.java.attribute.descriptor.lambda.parameter:
    text: 매개 변수//Lambda parameter
options.java.attribute.descriptor.reassigned.local.variable:
    text: 변수//Reassigned local variable
options.java.attribute.descriptor.reassigned.parameter:
    text: 매개 변수//Reassigned parameter
options.jsp.attribute.descriptor.el.background:
    text: 표현식 언어//배경
options.jsp.attribute.descriptor.el.bounds:
    text: 표현식 언어//Bounds
options.jsp.attribute.descriptor.el.brackets:
    text: 표현식 언어//대괄호
options.jsp.attribute.descriptor.el.comma:
    text: 표현식 언어//쉼표
options.jsp.attribute.descriptor.el.dot:
    text: 표현식 언어//Dot
options.jsp.attribute.descriptor.el.identifier:
    text: 표현식 언어//Identifier
options.jsp.attribute.descriptor.el.keyword:
    text: 표현식 언어//키워드
options.jsp.attribute.descriptor.el.number:
    text: 표현식 언어//숫자
options.jsp.attribute.descriptor.el.parens:
    text: 표현식 언어//Parentheses
options.jsp.attribute.descriptor.el.string:
    text: 표현식 언어//문자열
options.xml.attribute.descriptor.comment:
    text: 주석
options.xml.attribute.descriptor.tag:
    text: 꼬리표
